version: 2

sources:
  - name: airbyte_raw
    schema: RAW
    tables: 
      - name: customer
        columns:
          - name: c_customer_sk
            tests:
              - not_null
              - unique
          - name: C_CURRENT_ADDR_SK
            tests:
              - relationships:
                  to: source('airbyte_raw','customer_address')
                  field: ca_address_sk
          - name: C_CURRENT_CDEMO_SK
            tests:
              - relationships:
                  to: source('airbyte_raw','customer_demographics')
                  field: cd_demo_sk
                  accept_null: true
                  where: "cd_demo_sk <= 480200"  # Only test for valid demographic keys
      # ... (rest of the file remains unchanged)